version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arch-python-app
    ports:
      - "8001:8001"
      - "27017:27017"
      - "8081:8081"
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-in-Docker if needed
    environment:
      - PYTHONPATH=/app
      - PATH=/opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    restart: unless-stopped
    networks:
      - app-network
    
  # Optional: MongoDB service if you're using it (port 27017 suggests this)
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    networks:
      - app-network

  # Optional: Ollama service (since you're installing Ollama in the Dockerfile)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - app-network
    # Uncomment below if you have GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  ollama_data:
