

chunks = [
    "Canada is a country in North America with ten provinces and three territories.",
    "Ottawa is the capital city of Canada.",
    "Canada is known for its natural beauty and vast landscapes.",
    "Toronto is the largest city in Canada.",
    "Vancouver is a major city located in British Columbia.",
    "Montreal is a French-speaking city in Quebec.",
    "Canada has two official languages: English and French.",
    "The Canadian dollar is the official currency.",
    "Niagara Falls is a famous tourist attraction on the border of Ontario and the USA.",
    "Canada is the second-largest country in the world by land area.",
    "Hockey is considered the national winter sport of Canada.",
    "The maple leaf is a national symbol and appears on the Canadian flag.",
    "Canada shares the longest undefended border with the United States.",
    "The Great Lakes are partially located in Canada.",
    "The Rocky Mountains stretch through western Canada.",
    "Banff National Park is located in Alberta.",
    "Canada is a parliamentary democracy and constitutional monarchy.",
    "The Prime Minister is the head of government.",
    "Justin Trudeau is a recent Prime Minister of Canada.",
    "Canada Day is celebrated on July 1st.",
    "The population of Canada is over 38 million.",
    "Indigenous peoples in Canada include First Nations, Inuit, and Métis.",
    "Canada's economy is highly developed and resource-rich.",
    "Forests cover about 38% of Canada's land area.",
    "Lakes and rivers occupy about 9% of Canada's surface area.",
    "The CN Tower is located in Toronto.",
    "Canada has a reputation for being polite and welcoming.",
    "Canada was founded on July 1, 1867.",
    "The Charter of Rights and Freedoms is part of Canada's constitution.",
    "The Royal Canadian Mounted Police is a federal law enforcement agency.",
    "Canada's national animal is the beaver.",
    "Canada has six time zones.",
    "The Yukon is one of Canada's northern territories.",
    "Nunavut is the largest and newest territory.",
    "Quebec is known for its strong French culture and language.",
    "The Trans-Canada Highway is the longest national highway in the world.",
    "Canada has universal healthcare.",
    "Canadian cuisine includes poutine and butter tarts.",
    "Tim Hortons is a popular coffee chain in Canada.",
    "The climate in Canada varies from arctic in the north to temperate in the south.",
    "Canada is a member of the G7, NATO, and the UN.",
    "Many movies are filmed in Vancouver and Toronto.",
    "Canada has hosted the Olympic Games three times.",
    "The Canadian Shield is a large geological area rich in minerals.",
    "The Parliament Buildings are located in Ottawa.",
    "Canada has more lakes than any other country.",
    "Education in Canada is publicly funded and managed by provinces.",
    "Canada ranks high in quality of life indices.",
    "The Laurentian Mountains are located in Quebec.",
    "Canada's forests are a major source of timber exports.",
    "Fishing and logging are important industries in the Atlantic provinces.",
    "Toronto is the financial hub of Canada.",
    "Calgary is known for its oil and gas industry.",
    "Saskatchewan is known for its vast prairie lands.",
    "Manitoba has many freshwater lakes and rivers.",
    "Newfoundland and Labrador is Canada's easternmost province.",
    "Prince Edward Island is the smallest province in Canada.",
    "British Columbia is bordered by the Pacific Ocean.",
    "Canada's Arctic region is home to polar bears and arctic foxes.",
    "The Canadian Space Agency contributes to international space research.",
    "The Group of Seven were famous Canadian landscape painters.",
    "Canada is known for high-quality maple syrup production.",
    "Toronto's multicultural population speaks over 140 languages.",
    "The University of Toronto is one of Canada's top universities.",
    "McGill University is a leading institution in Montreal.",
    "The St. Lawrence River is a major waterway for trade.",
    "The Bay of Fundy has the highest tidal range in the world.",
    "Ice hockey and lacrosse are official national sports.",
    "Canada has large deposits of natural gas and oil.",
    "The Athabasca Oil Sands are located in Alberta.",
    "Canada exports wood, wheat, and minerals worldwide.",
    "Canadian forests are home to moose, elk, and bears.",
    "Snowfall is common in most Canadian provinces during winter.",
    "The Canadian Broadcasting Corporation (CBC) is a public media network.",
    "Canada's postal code system includes letters and numbers.",
    "Recycling programs are widely practiced in Canada.",
    "The Canadian Arctic Archipelago includes many remote islands.",
    "Canada has protected marine and national parks.",
    "The Inuit population lives mostly in northern Canada.",
    "The West Coast has a milder climate than the rest of Canada.",
    "The 49th parallel forms part of the US-Canada border.",
    "Canadian high schools typically go up to Grade 12.",
    "University tuition is lower in Canada than in the U.S.",
    "The Canadian Senate reviews laws passed by the House of Commons.",
    "Provinces have jurisdiction over health, education, and infrastructure.",
    "Canada has a GST (Goods and Services Tax).",
    "Parks Canada manages national parks and historic sites.",
    "Whistler is a famous ski resort in British Columbia.",
    "French is the primary language in Quebec.",
    "Nova Scotia has a rich maritime history.",
    "Halifax is the capital of Nova Scotia.",
    "The Canada-U.S. border has many official land crossings.",
    "Canada has the tenth-largest economy in the world.",
    "The Canadian Pacific Railway united the country in the 1800s.",
    "Canada has strict environmental protection laws.",
    "Vancouver Island is known for whale watching.",
    "The Canadian health card provides access to medical care.",
    "Winter temperatures can drop below -30°C in parts of Canada.",
    "Canada has a multicultural immigration policy.",
    "Many Canadians live within 200 km of the US border.",
    "The Great Bear Rainforest is one of the largest coastal temperate rainforests.",
    "Canada has hosted many G20 and UN conferences.",
    "Polar bears are a symbol of Canadian wildlife.",
    "French immersion programs are popular in schools.",
    "The Pacific Rim National Park is located in British Columbia.",
    "Many Canadian cities have public bike-sharing programs.",
    "Toronto has a large film and television industry.",
    "The Canadian flag was adopted in 1965.",
    "Inuit art is an important part of Canadian culture.",
    "Canadian Thanksgiving is celebrated in October.",
    "The Rideau Canal becomes a skating rink in winter.",
    "Canada's national anthem is 'O Canada'.",
    "Canada's wilderness is home to over 70,000 species of plants and animals.",
    "The word 'Canada' comes from the Iroquoian word 'Kanata', meaning village.",
    "The Pacific Ocean borders Canada's west coast.",
    "Canada's national parks protect over 340,000 square kilometers of land.",
    "Churchill, Manitoba is known as the polar bear capital of the world.",
    "Lake Superior, shared with the U.S., is the world's largest freshwater lake by area.",
    "Canada's population density is one of the lowest in the world.",
    "Victoria is the capital city of British Columbia.",
    "Canada's literacy rate is among the highest globally.",
    "The Hudson Bay is a large inland sea in northeastern Canada.",
    "Canada produces over 70% of the world’s maple syrup.",
    "Mont-Tremblant is a popular ski resort in Quebec.",
    "Canada's Parliament consists of the Monarch, the Senate, and the House of Commons.",
    "Each Canadian province has its own Lieutenant Governor.",
    "Canada was part of the British Empire and gained full independence in 1982.",
    "Canada's legal system is based on English common law, except in Quebec, which follows civil law.",
    "Nunavut was separated from the Northwest Territories in 1999.",
    "The tallest mountain in Canada is Mount Logan in the Yukon.",
    "The Toronto Raptors won the NBA Championship in 2019.",
    "Canada has more than 2 million lakes.",
    "Canada's film and TV industry is heavily based in Vancouver and Toronto.",
    "Canadian passports rank high in global travel freedom indexes.",
    "The Group of Twenty (G20) includes Canada as a founding member.",
    "Canada’s forestry sector is a major contributor to its GDP.",
    "Icewine is a specialty dessert wine produced in Canadian vineyards.",
    "The Canadian Prairies are known for grain production.",
    "The Confederation Bridge connects Prince Edward Island to the mainland.",
    "The Canadian Forces consist of the Army, Navy, and Air Force.",
    "Canada ranks among the world's top oil producers.",
    "The Huron, Iroquois, and Algonquin were historic Indigenous nations.",
    "The Canadian Arctic is experiencing rapid climate change.",
    "Snowbirds are Canadians who travel south in winter.",
    "Canada has over 200 ethnic origins reported in the census.",
    "The Toronto Stock Exchange (TSX) is among the world's largest stock exchanges.",
    "The Inuit invented the kayak.",
    "Canadians celebrate multiculturalism through various festivals.",
    "Ottawa hosts Winterlude, an annual winter festival.",
    "The Canadian flag was raised for the first time on February 15, 1965.",
    "The RCMP was founded in 1873 as the North-West Mounted Police.",
    "The Canadian Charter of Rights and Freedoms was adopted in 1982.",
    "Canada is a safe country with a low crime rate.",
    "The Canadian Shield contains some of the world's oldest rocks.",
    "Moose are one of Canada's most iconic wildlife species.",
    "The Governor General represents the Monarch in Canada.",
    "Most Canadians live near the southern border.",
    "The Labrador Current keeps the Atlantic provinces cool.",
    "The Pacific salmon run is vital to the West Coast ecosystem.",
    "Canada has signed many environmental protection treaties.",
    "The Bank of Canada is the country’s central bank.",
    "Canada uses a parliamentary system of government.",
    "Toronto's PATH is the largest underground shopping complex in the world.",
    "The Inuktitut language is spoken in parts of the Arctic.",
    "French is the sole official language of Quebec.",
    "Lake Louise is a major tourist destination in Alberta.",
    "The Canadian Human Rights Act promotes equality.",
    "The Blue Nose was a famous Canadian racing schooner.",
    "Canada’s natural gas exports mainly go to the United States.",
    "The War of 1812 helped shape Canadian identity.",
    "Canada's healthcare system is publicly funded and provincially administered.",
    "The Arctic Ocean borders northern Canada.",
    "Canada has no official religion, but freedom of religion is protected.",
    "The Canadian Constitution includes both written and unwritten elements.",
    "Yonge Street in Ontario was once considered the longest street in the world.",
    "Canada's postal service dates back to 1867.",
    "The Order of Canada is one of the country's highest civilian honors.",
    "Many Canadian cities are bike-friendly.",
    "Canadian coins include the loonie and the toonie.",
    "The loonie is a $1 coin featuring a common loon.",
    "Terry Fox is a national hero who ran for cancer research.",
    "Canada has strong environmental policies on air and water quality.",
    "The Toronto International Film Festival (TIFF) is world-renowned.",
    "The CBC operates in both English and French.",
    "The highest court in Canada is the Supreme Court.",
    "Canadians vote in federal elections every four years.",
    "Parliament Hill is a popular tourist destination in Ottawa.",
    "The Canadian flag features a red maple leaf with red bars on either side.",
    "The Maritimes include Nova Scotia, New Brunswick, and PEI.",
    "Canada has a strong reputation for peacekeeping missions.",
    "The national motto of Canada is 'A Mari Usque Ad Mare'—From Sea to Sea.",
    "Canada legalized same-sex marriage nationwide in 2005.",
    "The Canadian Rockies are popular for skiing and hiking.",
    "The Calgary Stampede is a major rodeo and exhibition event.",
    "Canadians enjoy a high standard of living.",
    "The Trans-Canada Trail is one of the world’s longest recreational trails.",
    "The Canadian Grain Commission regulates grain handling.",
    "Canada's ports handle billions in trade every year.",
    "The Laurentian Plateau is rich in minerals.",
    "Saskatchewan has some of the flattest terrain in Canada.",
    "The Bay of Quinte is located in southeastern Ontario.",
    "The Rideau Canal is a UNESCO World Heritage Site.",
    "The Canadian government provides funding for Indigenous education.",
    "The Canadian Arctic is a focus of scientific research on climate change.",
    "The McKenzie River is the longest river system in Canada.",
    "Canadian federalism divides powers between national and provincial governments.",
    "Many Canadian cities rank among the world's most livable.",
    "The Canadian Forces actively participate in NATO exercises.",
    "Canada's minimum wage varies by province.",
    "The Charter of the French Language governs use of French in Quebec.",
    "Canada’s parks are home to grizzly bears, wolves, and caribou.",
    "Telemedicine is expanding access to care in rural Canadian communities.",
]
